/* ==========================================================
SMART LIGHT TICKET MONITORING SYSTEM
Shared Configuration
========================================================== */

window.APP_CONFIG = {
    chartLibrary: "chart.js",
    customerRegionsMap: {
      "5B Innovations": ["BCCC", "BSCC", "BWCC"],
      "Alcon": ["Alcon-Goa"],
      "Apex": ["Arani", "Avadi", "Nellikuppam", "Ponneri", "Sholinghur", "Sivakasi", "Thirukovilur", "UDU", "Ulundurpettai", "Vandavasi"],
      "Bajaj Electricals Ltd": ["Balangir", "Baliguda", "Basudevpur", "Bhadrak", "Binika", "Boudhgarh", "Chandbali", "Daspalla", "Dhamnagar", "G.Udayagiri", "Kantabanji NAC", "Khandapada", "Khariar", "Khariar Road", "Nayagarh", "Nuapada", "Odagaon", "Patnagarh", "Phulbani", "Ranpur", "Sonepur", "Tarbha", "Titilagarh", "Tusura", "Unknown"],
      "Balajee Electricals": ["Karur"],
      "Balaji Traders": ["HosurBT", "Unknown"],
      "Bangalore (BBMP)": ["Bommanahali", "EAST", "Unknown"],
      "CCMC": ["CJB", "ERO", "GOA", "Unknown"],
      "CSML": ["KSC", "KSCOthers", "Unknown"],
      "DEMO": ["Bajaj", "DEMO", "Unknown", "smDemo"],
      "Delight Engineering": ["Ambasamudram", "Colachal", "Kadayanallur", "Kollencode", "Kottakuppam", "Sengottai", "Sivakasi", "Thiruchendur", "Thirutanni", "Unknown"],
      "Demo-signify": ["Demo"],
      "ECMC": ["AOP", "ERO", "GOA", "Unknown", "VLR"],
      "FMDA": ["Haryana"],
      "GED": ["GOA"],
      "GMDA": ["Gurugram"],
      "Hariway Line (P) Ltd": ["Arcot", "Chidambaram", "Chinnamanur", "Cumbum", "Edappadi", "Jolarpet", "Kallakurichi", "Krishnagiri", "Mettur", "Periyakulam", "Tirumangalam", "Tirupathur", "Tiruvannamalai", "Unknown", "Vaniyambadi"],
      "Hruday Infra Resource Solution": ["Ambur", "Devakottai", "Gudiyatham", "Keelakarai", "Manamadurai", "Melvisharam", "Paramakudi", "Pernambut"],
      "IDCO": ["Odisha"],
      "Kozzby Construction": ["Nawada"],
      "Kumaran Industries": ["Tiruchchirappalli"],
      "Lucknow Nagar Nigam": ["Lucknow"],
      "MAA": ["CJB", "KSC", "MAA", "Unknown"],
      "MMC": ["MAD"],
      "Murugan Electrical": ["Kalakad"],
      "NHAI": ["Chengalpattu-PIU", "Kancheepuram"],
      "Neri Lighting": ["Ayodhya"],
      "Orient Electric Limited": ["ANN - Pack 1", "Ayodhya Nagar Nigam"],
      "Public": ["Ambur", "Arcot", "Coimbatore", "Demo", "Gudiyatham", "Jolarpet", "Thiruvannamalai", "Tirumangalam"],
      "RCCL": ["AOP", "GOA", "Unknown"],
      "RN Electrical": ["CCMC"],
      "RS Enterprises": ["Ramanathapuram", "Sivagangai"],
      "Sabhari Electricals": ["Coimbatore"],
      "Salzer": ["Tiruppur"],
      "Sanity test Demo": ["KCT", "NSNPalayam", "NSNpalayamQR", "STD1", "STD2", "Unknown"],
      "SEMC": ["DEMO", "SEMC-Demo1", "Schnell-Demo", "Spectrum-Demo"],
      "SLM": ["SLM"],
      "SMPK Kolkata": ["NethajiSubashDock"],
      "SR United Infra Developers": ["Cuddalore", "Dharapuram", "Madurantakam", "Panruti", "Tambaram", "Thiruverkadu", "UDU", "Virudhachalam"],
      "STP": ["Coonoor"],
      "Schnell": ["ATM", "Avadi", "Ayodhya Nagar Nigam", "Dharapuram", "Erode", "Hosur", "Kulithalai", "Madukkarai", "Madurai", "Mettupalayam", "NAR", "Nelliyalam", "Pallapatti Municipality", "Pollachi", "Ponneri", "Punjaipuliyampati", "Sankarankovil", "THI", "Tiruppur", "Tiruppur1", "Vellore", "Villupuram", "Virudhachalam"],
      "Signify": ["TN"],
      "Suntastic": ["Karamadai", "Karumathampatti"],
      "Surya Roshni": ["Anandpur", "Balasore", "Barbil", "Baripada", "Champua", "Jajpur", "Jaleswar", "Joda", "Karanjia", "Keonjhargarh", "Nilgiri", "Raigangpur", "Remuna", "Soro", "UDU", "Udala", "Unknown", "Vyasnagar"],
      "Surya Roshni - GF": ["Baripada-GF", "Karanjia-GF", "Keonjhargarh-GF", "Nilgiri-GF", "Rairangpur-GF", "Remuna-GF", "Soro-GF", "Udala-GF", "Vyasnagar-GF"],
      "System": ["AOP", "ATM", "Arcot", "CJB", "Chengalpattu-PIU", "Coimbatore", "DEMO", "EAST", "G.Udayagiri", "GOA", "Gurugram", "Hosur", "Kantabanji NAC", "Khandapada", "MAA", "Madurantakam", "NAR", "Nilgiri-GF", "Odagaon", "Pernambut", "Sivakasi", "TUP", "Unknown", "VLR", "Villupuram"],
      "TCMC": ["AOP", "CJB", "GOA", "TUP"],
      "TJV": ["TJV"],
      "TVL": ["TVL"],
      "UMC": ["UDU"],
      "Udupi Tollway Private Limited": ["UTPL"],
      "VCMC": ["VLR"],
      "crompton": ["GOA", "Ranchi", "Unknown"]
    }
};
